### PR TITLE
Use Cassette to record animations

### PR DESCRIPTION
**Pull request by tkoolen**
I realized today that Cassette is *exactly* the right tool to record visualizations. Even the name fits.

I've disliked `AnimationFrameVisualizer` for a while; it's almost a `Visualizer` but not quite, and it makes it harder to set up animations for specific purposes. For example, in MeshCatMechanisms we have a `setanimation!` overload with the lines:

```julia
        atframe(animation, visualizer(mvis), frame) do frame_visualizer
            _render_state!(MechanismVisualizer(state(mvis), frame_visualizer))
        end
```

Even though we already had a `MechanismVisualizer` all set up and ready to go, we're creating a new one at every frame from `frame_visualizer`, just so we can use the same API to modify the underlying `AnimationFrameVisualizer`. This makes `MechanismVisualizer` more complicated than it needs to be (parameterized on the type of its `visualizer` field), and it means that you can't really do any useful work in the `MechanismVisualizer` constructor.

The basic goal of `AnimationFrameVisualizer` is to intercept calls to `setprop!` and `settransform!`, and Cassette is designed for just that. With Cassette, there's no longer a need to parameterize `MechanismVisualizer` (or any `MeshCat.Visualizer`-holder) on the visualizer type in order to support animation, and

```julia
atframe(anim, vis, 30) do frame
    settransform!(frame[:box1], Translation(0., 1, 0))
end
```

simplifies to

```julia
atframe(anim, 30) do
    settransform!(vis[:box1], Translation(0., 1, 0))
end
```

I kept the old `AnimationFrameVisualizer` for now, but I actually think we can just get rid of it entirely in a pretty-much backwards-compatible fashion by just returning `vis` as `frame_vis` in the four-argument version of `atframe`.

### CODE REVIEW

**Comment by rdeits** [comment]
Wow, this is a really good idea! I had never thought of handling animation this way, but it makes a lot of sense. If this works well for you I'm happy to delete the old AnimationVisualizer. 

I think this should also make animating arrows easier, since they previously had the same problem that MechanismVisualizer did, where you had to recreate the ArrowVisualizer inside each frame of the animation.

**Comment by tkoolen** [comment]
Added the deprecation and removed `AnimationFrameVisualizer`. For the `atframe` method that takes a `Path` we unfortunately have to throw an error.

**Comment by tkoolen** [comment]
I've been using this for a couple of days now and haven't run into any issues (after working around and later fixing https://github.com/jrevels/Cassette.jl/issues/89). So if you're also happy with this change, I'd love to get it merged.

**Comment by rdeits** [comment]
Yeah, this is great. Merging!

**Pull request merged**
