### PR TITLE
Add Blink.jl as a dependency to work around Pkg resolver issues.

### PR DESCRIPTION
**Pull request by tkoolen**
It seems the resolver can't handle our test dependencies. I was looking into the recent Travis failures for this package (https://travis-ci.org/rdeits/MeshCat.jl/jobs/628465886#L323-L338),
but also for dependent packages (https://travis-ci.org/JuliaRobotics/MeshCatMechanisms.jl/jobs/629392015#L347-L358). I couldn't really make sense of the unsatisfiable requirements message produced by the resolver, and I eventually found out that simply adding Blink as an explicit dependency of MeshCat makes tests pass again.

### CODE REVIEW

**Comment by tkoolen** [comment]
Opened https://github.com/JuliaGizmos/Blink.jl/issues/226 in response to Travis error on 1.0.

**Comment by tkoolen** [comment]
Since this at least fixes the build for OSX and Linux, not only for this package but (hopefully) for all dependencies, I'm going to go ahead and merge this now.

**Comment by tkoolen** [comment]
Apologies, the Travis error that I thought was on 1.0 was actually on 1.3, and should be resolved by https://github.com/JuliaGizmos/Blink.jl/pull/225.

**Comment by rdeits** [comment]
:+1: thanks for doing this!

**Pull request merged**
