### PR TITLE
Try replacing Mux and WebSockets with pure HTTP.jl

### LINKED ISSUE #236: Understand why the GitHub CI Windows runner started failing all of a sudden
Despite corresponding to the same commit, these two pipeline jobs have different outcomes on the Windows runner:
- https://github.com/rdeits/MeshCat.jl/actions/runs/4739284721/jobs/8413967357 (success)
- https://github.com/rdeits/MeshCat.jl/actions/runs/4739284721/jobs/8891545831 (fail)

For now, I will disable this Windows runner.

### LINKED ISSUE #242: Consider removing Blink.jl in favor of Electron.jl
Blink.jl introduces a lot of dependencies (WebIO.jl, WebSockets.jl, JSExpr.jl, etc.) and a lot of resulting complexity in terms of package compatibility (e.g. https://github.com/rdeits/MeshCat.jl/pull/241#issue-1709262147 ). 

We're not getting any benefit from all of the complicated WebIO stuff that Blink implements (e.g. its magical javascript-to-julia translation tool). We're only using it as an easy way to create a standalone web visualizer outside of a browser.

https://github.com/davidanthoff/Electron.jl seems like a better way to achieve the same thing--it also provides a standalone web viewer, but it depends on far less and it has far less magic under the hood. I think we should switch our tests over to use that package.

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #235 (by removing WebSockets.jl entirely). 

Fixes #236, ~~I hope (by allowing us to upgrade Blink.jl to v0.12.6)~~. Edit: Blink.jl is gone, so the problem is gone too. 

This PR rewrites the core web server to only use HTTP.jl, eliminating the dependencies on Mux.jl and WebSockets.jl. I'm hoping this will avoid the issues we've seen in recent versions of those packages (https://github.com/rdeits/MeshCat.jl/issues/234, https://github.com/rdeits/MeshCat.jl/issues/233), and it should allow us to benefit from the fact that HTTP.jl seems to be much more reliably updated.

We were previously using Mux.jl to handle routing the basic URLs that the meshcat javascript needs, but the HTTP.jl `Router` class works just as well. Dispatching streams to the HTTP or websocket handler is also pretty easy without using Mux.jl at all. And the actual WebSocket implementation is now provided by HTTP.jl, so we don't need WebSockets.jl at all. 

~~The downside is that we have to upgrade the Julia requirement to 1.8 due to Blink requiring WebIO which requires WebSockets.jl (which we're not actually using) which requires Julia 1.8.2.~~ Edit: Removed Blink.jl in favor of Electron.jl to fix this (fixes #242 ).

### CODE REVIEW

**Comment by rdeits** [comment]
@ferrolho would you mind helping me test this out? I've made sure the very basic stuff like opening (and re-opening) a visualizer works, but I won't have time to do much more in the next day or two.

**Comment by rdeits** [comment]
Turns out it was easy to eliminate the dependency on Blink.jl entirely, so I did that. We should be able to support Julia 1.6 again.

**Comment by ferrolho** [comment]
> **Note**
> I am continuing to update/edit this comment as I test.

Here's a summary of my tests:

Using the Julia REPL for the commands + Chrome to open the visualiser:
- Basic opening/closing works;
- README.md examples work;
- Saving screenshot/scene works;
- Loading a scene does not work;
  - I don't use this regularly, so it may have been broken before. _To be checked._
- Closing/reopening tab on same address works;
- Starting a second visualiser from the same REPL works.

**Comment by rdeits** [comment]
Thank you--that's extremely helpful! 

I tested this on Windows as well and verified that https://github.com/rdeits/MeshCat.jl/issues/234 is still fixed on this branch. I'll see if I can fix that IOError after closing the electron window and then merge this.

**Pull request merged**
