### PR TITLE
update to the latest meshcat js

### PR DESCRIPTION
**Pull request by rdeits**
Includes https://github.com/rdeits/meshcat/pull/58 and https://github.com/rdeits/meshcat/pull/60

### CODE REVIEW

**Comment by rdeits** [comment]
Blocked by https://github.com/JuliaGizmos/WebIO.jl/issues/337 :slightly_frowning_face:

**Comment by tkoolen** [comment]
Also blocked by https://github.com/rdeits/MeshCat.jl/pull/115#issuecomment-518076100, sorry.

**Comment by tkoolen** [comment]
Fix for https://github.com/rdeits/MeshCat.jl/pull/115#issuecomment-518076100 in https://github.com/rdeits/MeshCat.jl/pull/124.

**Comment by tkoolen** [comment]
https://github.com/JuliaWeb/MbedTLS.jl/issues/208

**Comment by rdeits** [comment]
I think the "explicit requirement" that is restricting MbedTLS to an incompatible version must be coming from the `Manifest.toml`. It's likely that there isn't a single `Manifest.toml` that will give compatible versions for Julia 1.0, 1.1, and 1.2, so perhaps this is a case where being over-cautious by storing the Manifest is not helping. I'm going to try just removing the Manifest from the repo to see if that gets things working again.

**Comment by rdeits** [comment]
There's still something wrong here. The `test/visualizer.jl` tests are supposed to render the same scene in a browser window and a Blink window, but now the browser websocket connection closes  and doesn't render anything. There might be something broken in the Mux integration. Boo.

**Comment by rdeits** [comment]
This might be https://github.com/JuliaGizmos/WebIO.jl/issues/343

**Comment by tkoolen** [comment]
Ah, I guess I was working around that issue with https://github.com/rdeits/MeshCat.jl/commit/1108156c7788f7f2ab1b3d3c2483f9d981c0040d. This is quite the saga.

**Comment by rdeits** [comment]
Given that things are subtly broken in master (ref #127 ) and this is a step in the right direction, I'm going to merge this PR and then work on things from there.

**Pull request merged**
