### PR TITLE
added setobject! for HomogenousMesh that uses the color in HMesh

### PR DESCRIPTION
**Pull request by ryanelandt**

### CODE REVIEW

**Comment by tkoolen** [comment]
Could you add a test that covers this code?

**Comment by ryanelandt** [comment]
Added one. I'll work on getting better at remembering to do that.

**Comment by tkoolen** [comment]
Thanks, looks good to me. @rdeits?

**Comment by rdeits** [comment]
Thanks @ryanelandt! I actually would prefer to move this logic around a bit--having a specialization for `setobject! ` seems a bit odd, but we can implement the same behavior by instead implementing `Object(g::HomogenousMesh)` which is internally called by `setobject!`. That makes a bit more sense to me and has the further benefit of being something we can test more easily.

**Comment by rdeits** [comment]
I'll open a PR against your branch with the change I'm proposing.

**Comment by ryanelandt** [comment]
Adding MeshCat.material fixes the tests on all versions but 0.6. I don't know why the color isn't being set of 0.6.

Alternatively, removing the 0.6 tests from Travis will fix this issue.

**Comment by rdeits** [comment]
Hm, that's very strange. I'll check it out locally. I'd rather not drop 0.6 just because we don't understand what's going on.

**Comment by rdeits** [comment]
Oh, looks like a GoemetryTypes bug that got fixed since the last 0.6 compatible version. The `color` argument to HomogenousMesh just doesn't seem to do anything. I'll update our test to avoid the issue. 

That said, I'm open to dropping 0.6 support from MeshCat whenever it's convenient to do so.

**Pull request merged**
