### PR TITLE
Updates Rotations (1.1 -> 1.3) and Julia (1.5 -> 1.6) compat

### PR DESCRIPTION
**Pull request by ferrolho**

### CODE REVIEW

**Comment by ferrolho** [comment]
Apropos #214.

**Comment by ferrolho** [comment]
I bumped the `julia` compat as well because [Rotations@1.3.0](https://github.com/JuliaGeometry/Rotations.jl/releases/tag/v1.3.0) has dropped support for julia `< 1.6`.

**Comment by zsz00** [comment]
@rdeits can you review ??

**Comment by rdeits** [comment]
I ended up merging this with some other compat fixes in https://github.com/rdeits/MeshCat.jl/pull/232

**Pull request closed without merging**
