### PR TITLE
Compatibility updates for GeometryBasics 

### PR DESCRIPTION
**Pull request by ferrolho**
Renames `Point3f0` to `Point3f`, following https://github.com/JuliaGeometry/GeometryBasics.jl/pull/97.

I did run the script provided in the PR link above to rename other types, but these were the only occurrences that needed renaming.

### CODE REVIEW

**Comment by ferrolho** [comment]
I should mention that watching this package's unit tests running was the most entertaining unit testing I have ever experienced.

Screenshot from 2021-12-01 14-53-02

**Comment by ferrolho** [comment]
Hmm, do you know why the above are failing, @rdeits? I'm guessing it's something with the GitHub actions since all tests passed on my local machine.

**Comment by ferrolho** [comment]
Never mind what I said in the comment above. This is now ready to be merged.

**Comment by ferrolho** [comment]
When this is merged, we can also just close https://github.com/rdeits/MeshCat.jl/pull/201.

**Comment by rdeits** [comment]
Thank you again!

**Pull request merged**
